//! Criterion benchmarks for inverse kinematics: the iterative damped
//! least-squares solver and the closed-form analytic 6R solver, both targeting a
//! reachable pose on the `showcase6` arm.
use caliper_ik::{IkOpts, analytic_ik_6r, ik};
use caliper_kinematics::fk_tip;
use caliper_model::Model;
use criterion::{Criterion, black_box, criterion_group, criterion_main};
use std::path::Path;

fn load(name: &str) -> Model {
    let p = format!(
        "{}/../../oracle/fixtures/robots/{}",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    Model::from_urdf(Path::new(&p)).expect("load fixture")
}

fn bench_ik(c: &mut Criterion) {
    let m = load("showcase6.urdf");
    let frame = m.tip_frame();
    // A reachable target generated by FK from a known configuration.
    let q_true = [0.3_f64, -0.5, 0.7, 0.2, 0.4, -0.3];
    let target = fk_tip(&m, &q_true);
    let seed = [0.0_f64, -0.2, 0.4, 0.0, 0.2, 0.0];
    let opts = IkOpts::default();

    c.bench_function("ik_dls/showcase6", |b| {
        b.iter(|| {
            ik(
                black_box(&m),
                black_box(frame),
                black_box(&target),
                black_box(&seed),
                black_box(&opts),
            )
        })
    });

    c.bench_function("analytic_ik_6r/showcase6", |b| {
        b.iter(|| {
            analytic_ik_6r(
                black_box(&m),
                black_box(frame),
                black_box(&target),
                Some(black_box(&seed)),
            )
        })
    });
}

criterion_group!(benches, bench_ik);
criterion_main!(benches);
